---
- name: Configure dotfiles
  tags: dotfiles
  block:
    - name: Install stow
      community.general.homebrew:
        name: stow
        state: present

    - name: Clone dotfiles repo
      ansible.builtin.git:
        repo: https://github.com/connormeredith/dotfiles
        dest: ~/.dotfiles
        update: true
        version: master

    - name: Stow dotfiles
      ansible.builtin.shell: cd $HOME/.dotfiles && ./setup
